apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: playground-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "Server";
spec:
  tls:
  - hosts:
    - play.ballerina.io
    secretName: letsencrypt-prod
  rules:
  - host: play.ballerina.io
    http:
      paths:
      - path: /
        backend:
          serviceName: ballerina-playground-webserver-service
          servicePort: 80
      - path: /compiler
        backend:
          serviceName: ballerina-playground-compiler-service
          servicePort: 80
      - path: /controller
        backend:
          serviceName: ballerina-playground-controller-service
          servicePort: 80
      - path: /executor
        backend:
          serviceName: ballerina-playground-executor-service
          servicePort: 80
      - path: /gists
        backend:
          serviceName: ballerina-playground-gists-service
          servicePort: 80