apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playground-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "Server";
spec:
  tls:
  - hosts:
    - play.ballerina.io
    secretName: letsencrypt-prod
  rules:
  - host: play.ballerina.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ballerina-playground-webserver-service
            port:
              number: 80
      - path: /compiler
        pathType: Prefix
        backend:
          service:
            name: ballerina-playground-compiler-service
            port:
              number: 80
      - path: /controller
        pathType: Prefix
        backend:
          service:
            name: ballerina-playground-controller-service
            port:
              number: 80
      - path: /executor
        pathType: Prefix
        backend:
          service:
            name: ballerina-playground-executor-service
            port:
              number: 80
      - path: /gists
        pathType: Prefix
        backend:
          service:
            name: ballerina-playground-gists-service
            port:
              number: 80
