apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: techops@wso2.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
